force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/_tests_/LocationGeocodeAdressTests.cls
@isTest
public with sharing class LocationGeocodeAdressTests {
    @isTest
    private static void testCoventToGeolocation() {
        // Arrange
        List<Location__c> locs = VotingDataFactory.createLocations();
        Test.setMock(HttpCalloutMock.class, new GeolocationCalloutMock());

        // Act
        Test.startTest();
        LocationGeocodeAddress.DoAddressGeocode(locs[0].Id);
        Test.stopTest();

        // Assert
        Location__c geoLocation = [
            SELECT Name, Address__c, Postion__Latitude__s
            FROM Location__c
            WHERE id = :locs[0].Id
            Limit 1
        ];
        System.assertEquals(geoLocation.Postion__Latitude__s, 49.2328817);
    }
}