force-app/main/default/objects/Campaign_Location__c/Campaign_Location__c.object-meta.xml
<CustomObject>
    <label>Campaign Location</label>
    <nameField>
        <label>Campaign Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Campaign_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserCampaignController.cls
public with sharing class UserCampaignController {
    @AuraEnabled
    public static List<SObject> getUserByCampaign(String campaignId) {
        return getCampaignUsers(campaignId);
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getUserByCampaignCacheable(String campaignId) {
        return getCampaignUsers(campaignId);
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getPotentialCampaignUsers() {
        return [
            SELECT Id, PermissionSetId, PermissionSet.Name, AssigneeId, Assignee.Name
            FROM PermissionSetAssignment
            WHERE PermissionSet.Name = :Constants.VOTER_PERMISSION_SET
                OR PermissionSet.Name = :Constants.CONFIGURATOR_PERMISSION_SET
                OR PermissionSet.Name = :Constants.MODERATOR_PERMISSION_SET
                OR PermissionSet.Name = :Constants.Analyst_PERMISSION_SET
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled
    public static void saveCampaignLocations(List<Campaign_Location__c> campaignLocations, Id campaignId) {
        try {
            List<Campaign_Location__c> prevCampaignLocations = [
                SELECT Id
                FROM Campaign_Location__c
                WHERE Campaign_Id__c = :campaignId
            ];

            delete prevCampaignLocations;
            insert campaignLocations;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void saveCampaignUsers(List<User_Campaign__c> campaignUsers, Id campaignId) {
        try {
            List<User_Campaign__c> prevCampaignUsers = [
                SELECT Id
                FROM User_Campaign__c
                WHERE Campaign_Id__c = :campaignId
            ];

            delete prevCampaignUsers;
            insert campaignUsers;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getUserCampaignRecordType() {
        return [
            SELECT Id, Name
            FROM RecordType
            WHERE sObjectType = :Constants.USER_CAMPAIGN_TYPE
        ];
    }

    private static List<SObject> getCampaignUsers(String campaignId) {
        return [
            SELECT Name, User_Id__c, RecordType.Name, User_Id__r.Name, CreatedBy.Name
            FROM User_Campaign__c
            WHERE Campaign_Id__c = :campaignId
            WITH SECURITY_ENFORCED
        ];
    }
}