force-app/main/default/objects/Campaign_Location__c/Campaign_Location__c.object-meta.xml
<CustomObject>
    <label>Campaign Location</label>
    <nameField>
        <label>Campaign Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Location_Capaigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Campaign_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/_tests_/UserCampaignControllerTests.cls
@isTest
private class UserCampaignControllerTests {
    @isTest
    static void TestGetUserByCampaign() {
        // Arrange
        User_Campaign__c testUserCampaign = VotingDataFactory.creatCampaignWithUsers();

        // Act
        List<SObject> userCampaigns = UserCampaignController.getUserByCampaign(testUserCampaign.Campaign_Id__c);

        // Assert
        System.assertEquals(1, userCampaigns.size());
        System.assertEquals(testUserCampaign.Name, userCampaigns[0].get('Name'));
        System.assertEquals(testUserCampaign.User_Id__c, userCampaigns[0].get('User_Id__c'));
    }

    @isTest
    static void TestGetPotentialCampaignUsers() {
        // Act
        List<SObject> users = UserCampaignController.getPotentialCampaignUsers();

        // Assert
        System.assertNotEquals(0, users.size());
    }

    @isTest
    static void TestGetUserCampaignRecordType() {
        // Act
        List<SObject> roles = UserCampaignController.getUserCampaignRecordType();

        // Assert
        System.assertNotEquals(0, roles.size());
    }

    @isTest
    static void TestSaveCampaignUsers() {
        // Arrange
        User_Campaign__c insertedUserCampaign = VotingDataFactory.creatCampaignWithUsers();

        String newUserCampaignName = 'New User Campaign';
        User_Campaign__c newUserCampaign = new User_Campaign__c(
            Name = newUserCampaignName,
            Campaign_Id__c = insertedUserCampaign.Campaign_Id__c,
            User_Id__c = insertedUserCampaign.User_Id__c
        );

        List<User_Campaign__c> newUsers = new List<User_Campaign__c>{ newUserCampaign };

        // Act
        UserCampaignController.saveCampaignUsers(newUsers, insertedUserCampaign.Campaign_Id__c);

        // Assert
        List<User_Campaign__c> populatedUsers = [
            SELECT Id, Name
            FROM User_Campaign__c
        ];
        System.assertEquals(1, populatedUsers.size());
        System.assertEquals(newUserCampaignName, populatedUsers[0].Name);
    }

    @isTest
    static void TestSaveCampaignLocations() {
        // Arrange
        Campaign_Location__c insertedCampaignLocation = VotingDataFactory.createCampaingWithLocation();

        Campaign_Location__c newCampaignLocation = new Campaign_Location__c(
            Location_Id__c = insertedCampaignLocation.Location_Id__c,
            Campaign_Id__c = insertedCampaignLocation.Campaign_Id__c
        );

        List<Campaign_Location__c> newCampaignLocations = new List<Campaign_Location__c>{ newCampaignLocation };
        
        // Act
        UserCampaignController.saveCampaignLocations(newCampaignLocations, newCampaignLocation.Campaign_Id__c);

        // Assert
        List<Campaign_Location__c> populatedCampaignLocations = [
            SELECT Id, Name
            FROM Campaign_Location__c
        ];
        System.assertNotEquals(0, populatedCampaignLocations.size());
        System.assertNotEquals(insertedCampaignLocation.Name, populatedCampaignLocations[0].Name);
    }
}