force-app/main/default/objects/Campaign_Location__c/Campaign_Location__c.object-meta.xml
<CustomObject>
    <label>Campaign Location</label>
    <nameField>
        <label>Campaign Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Location_Capaigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LocationController.cls
public with sharing class LocationController {
    @AuraEnabled
    public static List<SObject> getPotentialCampaignLocations() {
        return [
            SELECT Id, Name
            FROM Location__c
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled
    public static List<SObject> getLocationByCampaign(String campaignId) {
        return [
            SELECT Name, Location_Id__r.Name, CreatedBy.Name
            FROM Campaign_Location__c
            WHERE Campaign_Id__c = :campaignId
            WITH SECURITY_ENFORCED
        ];
    }
}