force-app/main/default/objects/Campaign_Location__c/Campaign_Location__c.object-meta.xml
<CustomObject>
    <label>Campaign Location</label>
    <nameField>
        <label>Campaign Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/_tests_/LocationControllerTests.cls
@isTest
public with sharing class LocationControllerTests {
    @isTest
    static void TestGetPotentialLocations() {
        // Arrange
        List<Location__c> createdLocations = VotingDataFactory.createLocations();

        // Act
        List<SObject> result = LocationController.getPotentialCampaignLocations();

        // Assert
        System.assertNotEquals(0, result.size());
    }

    @isTest
    static void TestGetLocationByCampaign() {
        // Arrange
        Campaign_Location__c insertedCampaignLocation = VotingDataFactory.createCampaingWithLocation();

        // Act
        List<SObject> result = LocationController.getLocationByCampaign(insertedCampaignLocation.Campaign_Id__c);

        // Assert
        System.assertEquals(1, result.size());
    }
}