force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>User Campaigns</relationshipLabel>
    <relationshipName>User_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Campaign_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/_tests_/factories/UserCampaignDataFactory.cls
@IsTest
public with sharing class UserCampaignDataFactory {
    public static User_Campaign__c creatCampaignWithUsers() {
        Campaign__c testCampaign = new Campaign__c(Name='Test Campaign');
        insert testCampaign;

        Profile testProfile = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User testUser = new User(Alias = 'standt',
            Email='testing@testorg.com', 
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Los_Angeles',
            UserName='testUserCampaign@testorg.com',
            ProfileId = testProfile.Id);
        insert testUser;

        User_Campaign__c userCampaign = new User_Campaign__c(Name='Test User Campaign',
            Campaign_Id__c=testCampaign.Id,
            User_Id__c=testUser.Id);
        insert userCampaign;

        return userCampaign;
    }
}