force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>User Campaigns</relationshipLabel>
    <relationshipName>User_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Infrastructure/CampaignRepository.cls
public with sharing class CampaignRepository implements ICampaignRepository {

    public List<Id> getAssignedUserIds(Id campaignId, String userType){
        List<User_Campaign__c> userCampaigns = [
            SELECT User__c
            FROM User_Campaign__c
            WHERE Campaign__c = :campaignId AND RecordType.Name = :userType
        ];

        List<Id> ids = new List<Id>();

        for (User_Campaign__c uc : userCampaigns) {
            ids.add(uc.User__c);
        }

        return ids;
    }

    public void deleteAssignments(Id campaignId, List<String> userTypes){
        delete [
            SELECT Id
            FROM User_Campaign__c
            WHERE Campaign__c = :campaignId AND RecordType.Name IN :userTypes
        ];
    }

    public void setAssignments(List<Id> userIds, Id campaignId, String userType){
        if(userIds.size() == 0){
            return;
        }

        Id recordTypeId = Schema.SObjectType.User_Campaign__c.getRecordTypeInfosByDeveloperName()
            .get(userType).getRecordTypeId();

        List<User_Campaign__c> userCampaigns = new List<User_Campaign__c>();

        for (String userId : userIds) {
            User_Campaign__c uc = new User_Campaign__c(
                User__c = userId,
                Campaign__c = campaignId,
                RecordTypeId = recordTypeId
            );

            userCampaigns.add(uc);
        }

        insert userCampaigns;
	} 
}