force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Question should be part of many surveys and surveys can have more then one question, so we need to have jugged table.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Question and AnswerOption objects.</description>
    <label>Question Answer Option</label>
    <nameField>
        <label>Question Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer_Option_Id__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_Id__c</fullName>
    <label>Answer Option</label>
    <referenceTo>Answer_Option__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Answer_Option_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Survey and Question objects.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys Questions</relationshipLabel>
    <relationshipName>Surveys_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Question_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Id__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/_tests_/QuestionControllerTests.cls
@isTest
public with sharing class QuestionControllerTests {
    @isTest
    static void TestGetPotentialQuestions() {
        // Arrange
        List<Question__c> createdQuestions = VotingDataFactory.createQuestions();

        // Act
        List<SObject> result = QuestionController.getPotentialQuestions();

        // Assert
        System.assertNotEquals(0, result.size());
    }

    @isTest
    static void TestSaveQuestionAnswers() {
        // Arrange
        Question_Answer_Option__c insertedQuestionAnswer = VotingDataFactory.createQuestionsWithAnswer();

        Question_Answer_Option__c newQuestionAnswer = new Question_Answer_Option__c(
            Question_Id__c = insertedQuestionAnswer.Question_Id__c,
            Answer_Option_Id__c = insertedQuestionAnswer.Answer_Option_Id__c
        );

        List<Question_Answer_Option__c> newQuestionAnswers = new List<Question_Answer_Option__c>{ newQuestionAnswer };
        
        // Act
        QuestionController.saveQuestionAnswers(newQuestionAnswers, insertedQuestionAnswer.Question_Id__c);

        // Assert
        List<Question_Answer_Option__c> populatedQuestionAnswers = [
            SELECT Id, Name
            FROM Question_Answer_Option__c
        ];
        System.assertNotEquals(0, populatedQuestionAnswers.size());
        System.assertNotEquals(insertedQuestionAnswer.Name, populatedQuestionAnswers[0].Name);
    }

    @isTest
    static void TestGetQuestionBySurvey() {
        // Arrange
        Survey_Question__c insertedSurveyQuestion = VotingDataFactory.createSurveyWithQuestion();

        // Act
        List<SObject> questions = QuestionController.getQuestionBySurvey(insertedSurveyQuestion.Survey_Id__c);

        // Assert
        System.assertEquals(1, questions.size());
    }

    @isTest
    static void TestSaveSurveyQuestions() {
        // Arrange
        Survey_Question__c insertedSurveyQuestion = VotingDataFactory.createSurveyWithQuestion();

        Survey_Question__c newSurveyQuestion = new Survey_Question__c(
            Question_Id__c = insertedSurveyQuestion.Question_Id__c,
            Survey_Id__c = insertedSurveyQuestion.Survey_Id__c
        );

        List<Survey_Question__c> newSurveyQuestions = new List<Survey_Question__c>{ newSurveyQuestion };
        
        // Act
        QuestionController.saveSurveyQuestions(newSurveyQuestions, insertedSurveyQuestion.Survey_Id__c);

        // Assert
        List<Survey_Question__c> populatedSurveyQuestions = [
            SELECT Id, Name
            FROM Survey_Question__c
        ];
        System.assertNotEquals(0, populatedSurveyQuestions.size());
        System.assertNotEquals(insertedSurveyQuestion.Name, populatedSurveyQuestions[0].Name);
    }
}