force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Question should be part of many surveys and surveys can have more then one question, so we need to have jugged table.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Question and AnswerOption objects.</description>
    <label>Question Answer Option</label>
    <nameField>
        <label>Question Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Survey and Question objects.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys Questions</relationshipLabel>
    <relationshipName>Surveys_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Question_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Id__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionController.cls
public with sharing class QuestionController {
    @AuraEnabled
    public static List<SObject> getPotentialQuestions() {
        return [
            SELECT Id, Name
            FROM Question__c
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled
    public static void saveQuestionAnswers(List<Question_Answer_Option__c> answers, Id questionId) {
        try {
            List<Question_Answer_Option__c> prevAnswers = [
                SELECT Id
                FROM Question_Answer_Option__c
                WHERE Question_Id__c = :questionId
            ];

            delete prevAnswers;
            insert answers;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static List<SObject> getQuestionBySurvey(String surveyId) {
        return [
            SELECT Name, Question_Id__r.Name, CreatedBy.Name
            FROM Survey_Question__c
            WHERE Survey_Id__c = :surveyId
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled
    public static void saveSurveyQuestions(List<Survey_Question__c> surveyQuestions, Id surveyId) {
        try {
            List<Survey_Question__c> prevSurveyQuestion = [
                SELECT Id
                FROM Survey_Question__c
                WHERE Survey_Id__c = :surveyId
            ];

            delete prevSurveyQuestion;
            insert surveyQuestions;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}