force-app/main/default/objects/Refresh_Record_Event__e/Refresh_Record_Event__e.object-meta.xml
<CustomObject>
    <label>Refresh Record Event</label>
    <pluralLabel>Refresh Record Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserCampaignTriggerHandler.cls
public with sharing class UserCampaignTriggerHandler {
    @TestVisible private static List<Refresh_Record_Event__e> eventList = new List<Refresh_Record_Event__e>();

    public static void createRefreshRecordPlatformEvents(List<User_Campaign__c> newUserCampaigns){
        
        Refresh_Record_Event__e refreshEventObj = new Refresh_Record_Event__e();
        
        if(newUserCampaigns == null || newUserCampaigns.isEmpty())
            return;
                     
        for (User_Campaign__c user : newUserCampaigns) {
            refreshEventObj = new Refresh_Record_Event__e();
            refreshEventObj.Record_Id__c = user.Id;
            refreshEventObj.User_Id__c = UserInfo.getUserId();
            
            eventList.add(refreshEventObj);
        }
        
        try{
            if(eventList <> null && !eventList.isEmpty())
                EventBus.publish(eventList);
        }catch(Exception e){
            System.debug('Exception during publishing of refresh platform events-->'+e.getMessage());
        }
    }
}