force-app/main/default/objects/Answer_Option__c/Answer_Option__c.object-meta.xml
<CustomObject>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Question and AnswerOption objects.</description>
    <label>Question Answer Option</label>
    <nameField>
        <label>Question Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer_Option__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option__c</fullName>
    <label>Answer Option</label>
    <referenceTo>Answer_Option__c</referenceTo>
    <relationshipLabel>Question Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/_tests_/AnswerControllerTests.cls
@isTest
public with sharing class AnswerControllerTests {
    @isTest
    static void TestGetPotentialAnswers() {
        // Arrange
        List<Answer_Option__c> createdAnswers = VotingDataFactory.createAnswers();

        // Act
        List<SObject> result = AnswerController.getPotentialAnswers();

        // Assert
        System.assertNotEquals(0, result.size());
    }

    @isTest
    static void TestGetAnswersByQuestion() {
        // Arrange
        Question_Answer_Option__c insertedQuestionAnswer = VotingDataFactory.createQuestionsWithAnswer();

        // Act
        List<SObject> answerQuestion = AnswerController.getAnswersByQuestion(insertedQuestionAnswer.Question_Id__c);

        // Assert
        System.assertEquals(1, answerQuestion.size());
    }
}