force-app/main/default/objects/Answer_Option__c/Answer_Option__c.object-meta.xml
<CustomObject>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer_Option__c/fields/Anwer_Option_Text__c.field-meta.xml
<CustomField>
    <fullName>Anwer_Option_Text__c</fullName>
    <label>Anwer Option Text</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/Campaign_Location__c.object-meta.xml
<CustomObject>
    <label>Campaign Location</label>
    <nameField>
        <label>Campaign Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Campaign Locations</relationshipLabel>
    <relationshipName>Campaign_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Location__c/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Location_Capaigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>Question should be part of many surveys and surveys can have more then one question, so we need to have jugged table.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Question and AnswerOption objects.</description>
    <label>Question Answer Option</label>
    <nameField>
        <label>Question Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer_Option__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option__c</fullName>
    <label>Answer Option</label>
    <referenceTo>Answer_Option__c</referenceTo>
    <relationshipLabel>Question Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer_Option_Id__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_Id__c</fullName>
    <label>Answer Option</label>
    <referenceTo>Answer_Option__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Answer_Option_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answer Options</relationshipLabel>
    <relationshipName>Question_Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>One Campaign can have Many Surveys</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>Junction object between the Survey and Question objects.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys Questions</relationshipLabel>
    <relationshipName>Surveys_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question_Id__c.field-meta.xml
<CustomField>
    <fullName>Question_Id__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Question_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Surveys Questions</relationshipLabel>
    <relationshipName>Surveys_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Id__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/User_Campaign__c.object-meta.xml
<CustomObject>
    <label>User Campaign</label>
    <nameField>
        <label>User Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Campaign__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>User Campaigns</relationshipLabel>
    <relationshipName>User_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Campaign_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Campaign__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/_tests_/factories/VotingDataFactory.cls
@IsTest
public with sharing class VotingDataFactory {
    public static User_Campaign__c creatCampaignWithUsers() {
        Campaign__c testCampaign = new Campaign__c(Name = 'Test Campaign');
        insert testCampaign;

        Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User testUser = new User(
            Alias = 'standt',
            Email = 'testing@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testUserCampaign@testorg.com',
            ProfileId = testProfile.Id
        );
        insert testUser;

        User_Campaign__c userCampaign = new User_Campaign__c(
            Name = 'Test User Campaign',
            Campaign_Id__c = testCampaign.Id,
            User_Id__c = testUser.Id
        );
        insert userCampaign;

        return userCampaign;
    }

    public static List<Location__c> createLocations() {
        Location__c firstLocation = new Location__c(Name = 'First Location', Address__c = 'First Address');
        Location__c secondLocation = new Location__c(Name = 'Second Location', Address__c = 'Second Address');

        List<Location__c> locationList = new List<Location__c>{ firstLocation, secondLocation };
        insert locationList;

        return locationList;
    }

    public static List<Question__c> createQuestions() {
        Question__c firstQuestion = new Question__c(Name = 'First Question', Question_Text__c = 'First Test Question Text');
        Question__c secondQuestion = new Question__c(Name = 'Second Question', Question_Text__c = 'Second Test Question Text');

        List<Question__c> questionList = new List<Question__c>{ firstQuestion, secondQuestion };
        insert questionList;

        return questionList;
    }

    public static List<Answer_Option__c> createAnswers() {
        Answer_Option__c firstAnswer = new Answer_Option__c(Name = 'First Answer', Anwer_Option_Text__c = 'First Answer');
        Answer_Option__c secondAnswer = new Answer_Option__c(Name = 'Second Answer', Anwer_Option_Text__c = 'Second Answer');

        List<Answer_Option__c> answerList = new List<Answer_Option__c>{ firstAnswer, secondAnswer };
        insert answerList;

        return answerList;
    }

    public static Question_Answer_Option__c createQuestionsWithAnswer() {
        Question__c testQuestion = new Question__c(Name = 'First Question', Question_Text__c = 'First Test Question Text');
        insert testQuestion;

        Answer_Option__c testAnswer = new Answer_Option__c(Name = 'First Answer', Anwer_Option_Text__c = 'First Answer');
        insert testAnswer;

        Question_Answer_Option__c testQuestionAnswer = new Question_Answer_Option__c(
            Question_Id__c = testQuestion.Id,
            Answer_Option_Id__c = testAnswer.Id
        );
        insert testQuestionAnswer;

        return testQuestionAnswer;
    }

    public static Survey_Question__c createSurveyWithQuestion() {
        Campaign__c testCampaign = new Campaign__c(Name = 'Test Campaign');
        insert testCampaign;

        Question__c testQuestion = new Question__c(Name = 'First Question', Question_Text__c = 'First Test Question Text');
        insert testQuestion;

        Survey__c testSurvey = new Survey__c(Campaign_Id__c = testCampaign.Id, Name = 'First Survey');
        insert testSurvey;

        Survey_Question__c testSurveyQuestion = new Survey_Question__c(
            Question_Id__c = testQuestion.Id,
            Survey_Id__c = testSurvey.Id
        );
        insert testSurveyQuestion;

        return testSurveyQuestion;
    }

    public static Campaign_Location__c createCampaingWithLocation() {
        Campaign__c testCampaign = new Campaign__c(Name = 'Test Campaign');
        insert testCampaign;

        Location__c testLocation = new Location__c(Name = 'First Location', Address__c = 'First Address');
        insert testLocation;

        Campaign_Location__c testCampaingLocation = new 	Campaign_Location__c(
            Campaign_Id__c = testCampaign.Id,
            Location_Id__c = testLocation.Id
        );
        insert testCampaingLocation;

        return testCampaingLocation;
    }
}